### ISSUE TITLE
searchableAs method not working on entity repository

### ISSUE THREAD

**Issue by kfeng0806** [laravel-doctrine/scout#10]
hello, i have set "searchableAs" method in my entity repository, it returns another index name, but seems it not working as except.

repository of posts table:
```
class PostRepository extends SearchableRepository
{
    use Paginatable;

    /**
     * @return string
     */
    public function searchableAs()
    {
        return 'test_posts';
    }
}
```

when i use artisan command to importing data or just creating, updating entity with doctrine, it will still using its table name "posts" as index name.

PS: searching will takes overwrite index name, except creating, updating, deleting

**Comment by patrickbrouwers** [comment]
You need to link your repository with your entity for this to work:

```
/**
 * @ORM\Entity(repositoryClass="PostRepository")
 */
class Post { }
```

**Comment by kfeng0806** [comment]
tanks, i just linked them but now getting another error when importing data
```
[Symfony\Component\Debug\Exception\FatalThrowableError]
  Type error: Argument 3 passed to LaravelDoctrine\Scout\SearchableRepository::__construct() must be an instance of Laravel\Scout\EngineManager, none given, called in /.../vendor/doctrine/orm/lib/Doctrine/OR
  M/Repository/DefaultRepositoryFactory.php on line 68
```

in my service provider i have already bind EngineManager as 3th argument to my repository
```
public function register()
    {
        $this->app->bind(PostRepository::class, function($app) {
            return new PostRepository(
                $app['em'],
                $app['em']->getClassMetadata(Post::class),
                $app->make(\Laravel\Scout\EngineManager::class)
            );
        });
    }
```

**Comment by patrickbrouwers** [comment]
Hm, than I currently don't have a solution for this. Feel free to submit a PR if you find a solution. 
It should probably be something in the direction of:

- Registering `SearchSubscriber` als singleton
- adding a `setRepository(entityName, RepositoryName)` to the subscriber (keep array of repo's)
- then instead of $em->getRepository(), use the registered repository.

**Comment by kfeng0806** [comment]
i will looking for that, thank you :)

**Comment by isaackearl** [comment]
@kfeng0806 You ever find a good work around?  I'm running into the same thing...
