### ISSUE TITLE
Help with Elasticsearch

### ISSUE THREAD

**Issue by renanBritz** [laravel-doctrine/scout#14]
Hello!

I tested this package and it worked fine using Algolia Engine. But I'm having issues to run it with ElasticSearch engine.

Does anyone knows of a package to integrate Doctrine 2 with Scout and ElasticSearch? Any tutorials, anything? All I can find are implementations that assumes you're using Eloquent with Scout.

Regards!

**Comment by hskrasek** [comment]
@renanBritz Where did you wind up with this? Did you wind up making your own engine?
