### ISSUE TITLE
Scout 8.0?

### ISSUE THREAD

**Issue by kisuka** [laravel-doctrine/scout#20]
Scout 8.x is supported on Laravel 7.x. It gets Laravel 8 support in Scout 8.3.0.

Can we at least support up to Scout 8.2.1 for the Laravel 7.x tags? Technically Scout 8 came out the same day as Laravel 7.x, so it's a bit weird that 8.0 isn't supported here for Laravel 7.

**Comment by eigan** [comment]
Please try out `0.3.0` :)
