### ISSUE TITLE
Undefined method \"getScoutModelsByIds\". The method name must start with either findBy, findOneBy or countBy!

### ISSUE THREAD

**Issue by vincent-goossens** [laravel-doctrine/scout#23]
Hi,

After implementing the repository I am getting this error when performing a search, any idea?

Implemented the repository pattern and doing this:

`$this->app->bind(VintageProductSearchableRepositoryInterface::class, function() {
            return new VintageProductSearchableRepository(
                app('em'),
                app('em')->getClassMetaData(VintageProduct::class),
                app()->make(LaravelScoutEngineManager::class)
            );
        });`
        
$result = $this->vintageProductSearchableRepository->search('75cl')->get();

`    "message": "Undefined method \"getScoutModelsByIds\". The method name must start with either findBy, findOneBy or countBy!",
    "errors": {
        "exception": "BadMethodCallException",
        "file": "/var/www/vendor/doctrine/orm/lib/Doctrine/ORM/EntityRepository.php",
        "line": 283,
        "trace": [
            {
                "file": "/var/www/vendor/laravel/scout/src/Engines/AlgoliaEngine.php",
                "line": 206,
                "function": "__call",
                "class": "Doctrine\\ORM\\EntityRepository",
                "type": "->"
            },
            {
                "file": "/var/www/vendor/laravel/scout/src/Engines/Engine.php",
                "line": 136,
                "function": "map",
                "class": "Laravel\\Scout\\Engines\\AlgoliaEngine",
                "type": "->"`

**Comment by eigan** [comment]
Are you sure it is actually an instance of VintageProductSearchableRepository? Doesnt look like it. 
I am assuming this repository actually has a getScout... function now.

**Comment by vincent-goossens** [comment]
Hi @eigan ,

Thank you for your help.

The VintageProductSearchableRepository is instance of the VintageProductSearchableRepository has mentioned above through the repository pattern.

The search function is from the https://github.com/laravel-doctrine/scout/blob/master/src/SearchableRepository.php#L45

The getScoutModelsByIds  function is from here: https://github.com/laravel/scout/blob/10.x/src/Engines/AlgoliaEngine.php#L209

Any idea what is wrong here? 

![Screenshot 2024-02-29 at 19 54 29](https://github.com/laravel-doctrine/scout/assets/11923607/6342d055-bb6d-45b3-8c4f-e4da0fa6db23)
![Screenshot 2024-02-29 at 19 52 47](https://github.com/laravel-doctrine/scout/assets/11923607/61ff7d61-c7ea-49bd-9fdf-22b889cea725)
![Screenshot 2024-02-29 at 19 52 38](https://github.com/laravel-doctrine/scout/assets/11923607/9d3388e0-860f-4463-be1a-32854c02a021)
![Screenshot 2024-02-29 at 19 52 33](https://github.com/laravel-doctrine/scout/assets/11923607/d7d3697d-81b4-4451-ac9d-4dc3b9aa2a20)
![Screenshot 2024-02-29 at 19 52 24](https://github.com/laravel-doctrine/scout/assets/11923607/4cc39cf6-dcbc-45bc-8cd2-00fbd5173413)
![Screenshot 2024-02-29 at 19 52 19](https://github.com/laravel-doctrine/scout/assets/11923607/84aab94f-f437-44fe-b6d2-5d817a304ad8)

**Comment by eigan** [comment]
The error message you are receiving is thrown because the class it was called on does not implement the `getScoutModelsByIds` method. I am sorry but I cannot help you further. 

Personally I would set a breakpoint where this exception is thrown and inspect `$this`.
