### ISSUE TITLE
Error retrieving results when using UUIDs with Elasticsearch

### ISSUE THREAD

**Issue by brianvice** [laravel-doctrine/scout#3]
The ElasticsearchEngine class provided with laravel/scout exposes a map method that calls the offsetGet method on Illuminate\Support\Collection. When uuids are used as primary keys the uuid is passed as a parameter to the offsetGet method resulting in an error.

My quick and dirty fix for this was to write a "DoctrineElasticsearchEngine" class that extends the one provided with scout and then overwrite the map method as follows:

```
    /**
     * Map the given results to instances of the given model.
     *
     * @param  mixed  $results
     * @param  \Illuminate\Database\Eloquent\Model  $model
     * @return Collection
     */
    public function map($results, $model)
    {
        if (count($results['hits']) === 0) {
            return Collection::make();
        }

        $keys = collect($results['hits']['hits'])
                    ->pluck('_id')
                    ->values()
                    ->all();

        return $model->whereIn(
            $model->getKeyName(), $keys
        )->get()->keyBy($model->getKeyName());
    }
```

Essentially I just return early where the scout version does this:

```
...
        $models = $model->whereIn(
            $model->getKeyName(), $keys
        )->get()->keyBy($model->getKeyName());

        return Collection::make($results['hits']['hits'])->map(function ($hit) use ($model, $models) {
            return $models[$hit['_source'][$model->getKeyName()]];
        });
...
```

This returns a collection of results, but I would consider it only a temporary workaround.

In order to fully get this solution to work you need to resolve EntityManager as follows in your AppServiceProvider:

```
        resolve(EngineManager::class)->extend('doctrine_elasticsearch', function ($app) {
            return new DoctrineElasticsearchEngine(
                Elasticsearch::fromConfig(config('scout.elasticsearch.config')),
                config('scout.elasticsearch.index')
            );
        });
```

and then add 'doctrine_elasticsearch' as your driver in your .env file.

I hope this helps anyone stuck as I was. Perhaps someone can offer a more elegant solution?

**Comment by patrickbrouwers** [comment]
I'd suggest opening an issue/PR at scout as this is something that should be supported on Laravel/Scout side. 
I'd rather not supply an overruled doctrine implementation of ES engine.

**Comment by brianvice** [comment]
@patrickbrouwers I will try that. Thanks for getting back. I'll see if I can create a PR that allows both Eloquent models and Doctrine entities to use the same engine.

**Comment by charliekassel** [comment]
Hey @brianvice - hope you're well?
I'm facing exactly the same issue right now - did you get any further on this?
